version: 2.1
# orbs:
#   node: circleci/node@3.0.0
# workflows:
#   node-tests:
    jobs:
      build:
        docker: 
      #this is docker
           -image:circleci/node:12.15.0


      steps:
      -checkout
      -run:npm install
      -run:npm test
